modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="Nightware"
description='''
Data-driven Vitae for Minecraft modpacks. Define custom bosses via datapack JSON with GeckoLib animations and KubeJS scripting support.
'''

[[dependencies.${mod_id}]]
    modId="geckolib"
    type="required"
    versionRange="[4.8,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="kubejs"
    type="optional"
    versionRange="[2101,)"
    ordering="NONE"
    side="BOTH"
